name: appepunemiscan
description: Validador de Acceso Campus
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^7.0.0
  http: ^1.5.0
  auto_size_text: 3.0.0
  cached_network_image: ^3.4.1
  flutter_animate: ^4.5.2
  flutter_cache_manager: ^3.4.1
  flutter_plugin_android_lifecycle: ^2.0.32
  font_awesome_flutter: ^10.12.0
  from_css_color: 2.0.0
  go_router: ^16.3.0
  google_fonts: ^6.3.2
  intl: ^0.20.2
  json_path: ^0.8.0
  page_transition: ^2.2.1
  path_provider: ^2.1.5
  path_provider_android: ^2.2.20
  path_provider_foundation: ^2.4.3
  path_provider_platform_interface: ^2.1.2
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  shared_preferences_android: ^2.4.15
  shared_preferences_ios: 2.1.1
  shared_preferences_platform_interface: ^2.4.1
  shared_preferences_web: ^2.4.3
  url_launcher: ^6.3.2
  url_launcher_android: ^6.3.24
  url_launcher_ios: ^6.3.5
  url_launcher_platform_interface: ^2.3.2
  flutter_native_splash:
  flutter_hooks: ^0.21.3+1
  overlay_support: ^2.1.0
  flutter_sequence_animation: any
  scrollable_positioned_list:
  carousel_slider: ^5.1.1
  animate_do: ^4.2.0
  quickalert:
  cupertino_icons: ^1.0.5
  scratcher: ^2.3.0
  flutter_spinkit: ^5.1.0
  pinput: ^5.0.2
  get: ^4.7.2
  flutter_svg: ^2.2.2
  country_picker: ^2.0.27
  qr_widget: ^4.1.0
  dio:
  flutter_bloc: ^9.1.1
  equatable:
  shimmer: ^3.0.0
#  flutter_barcode_scanner: ^2.0.0
  mobile_scanner: ^5.2.3

#  flutter_barcode_scanner:
#    git:
#      url: https://github.com/FlutterFlow/flutter_barcode_scanner


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
  flutter_lints: ^6.0.0

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icon/ico.png'
  adaptive_icon_background: 'assets/icon/ico.png'

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/vacio.png
    - assets/images/default_image.png

  fonts:
    - family: RobotoRegular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: RobotoBold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: RobotoMedium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
    - family: RobotoLight
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
    - family: RobotoBlack
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf